"""Add github id and google id in users table

Revision ID: b66cd5605b24
Revises: 37c5c2a071fd
Create Date: 2025-12-30 00:06:31.999308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b66cd5605b24'
down_revision: Union[str, Sequence[str], None] = '37c5c2a071fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('github_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_id')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
